### ISSUE TITLE
Fedora support?

### ISSUE THREAD

**Issue by syedah314** [FrescoLogic/FL2000#17]
Is this supported for Fedora27/28 ?

**Comment by linux-mate** [comment]
If you compile probably it will work

I tried on arch linux latest linux-ck-haswell kernel and it seems to see device, and can detect wether or not display is connected.

Although i have this issue https://github.com/FrescoLogic/FL2000/issues/20. I think it's not a big issue. I hope authors will fix it easily.

**Comment by conbon-boncon** [comment]
It works. System - Fedora 36
