### ISSUE TITLE
Linear RGB instead of sRGB input

### ISSUE THREAD

**Issue by klogg** [FrescoLogic/FL2000#42]
Hello FL2000 team

It seems that FL2000 expects sRGB non-linear data in RGB24 mode. Is there any register setting that can be used to switch to linear RGB instead?

**Comment by sarman1998** [comment]
Hi Artem,
    No there is no control for this in fl2000 that I’m aware of.  If you are using one with an HDMI chip maybe the hdmi part has a setting like this. 

Eric

**Comment by klogg** [comment]
Hi Eric
Thanks for reply, I suspected that. Will try to to find a way to force Linux send sRGB, there are some new color management options in DRM/KMS.

**Comment by klogg** [comment]
@sarman1998 FYI - implemented conversion to RGB565 which is linear so works ok.
