### ISSUE TITLE
three display in Manjaro

### ISSUE THREAD

**Issue by SoyDiego** [FrescoLogic/FL2000#43]
Sorry, i'm newbie here...
Hi, i have two display working perfectly (my laptop and one monitor) and i wanna use one monitor more.

I bought an USB to VGA Adapter but I don't know how can I install or setup.
This is my adapter: https://www.newegg.com/p/2VR-00D3-00042 1

Is it possible use FL2000 in Manjaro to use 3 display?

**Comment by cesarcruzc** [comment]
Hey Diego,

Te funciono algo? tambien tengo linux, yo uso Pop OS!

**Comment by CanNuhlar** [comment]
No, It is not possible due to this driver lacking DRM support.

**Comment by SoyDiego** [comment]
> Hey Diego,
> 
> Te funciono algo? tambien tengo linux, yo uso Pop OS!

Hi Cesar, my solution was buy an HDMI to VGA adapter.
I couldn't with USB to VGA.

(Escribo en inglés por si a otra persona le sirve la respuesta :) )
