### ISSUE TITLE
OSX support? 

### ISSUE THREAD

**Issue by anderslundyo** [FrescoLogic/FL2000#9]
Hi - on work we recently bought a few, since it was sold to us with the promise of OSX compatibility. 
But after doing a little google search, we found it was not supported by mac. Anyone has a fix/can tweak this, so it can be used for mac?

**Comment by alextunyk** [comment]
I also bought one with promise of OSX but it appeared only windows. Is there any plan to add support for mac?

**Comment by LinJiabang** [comment]
FrescoLogic has macOS driver support .goto https://support.frescologic.com/portal/home

**Comment by astute-engineering** [comment]
That page is invalid. Could you please update the latest location of the driver?

**Comment by restuindrawan** [comment]
https://support.frescologic.com/portal/en/kb/articles/fl2000-mac-driver-beta-release

**Comment by ihor-yarovyi** [comment]
@LinJiabang Links are totally broken

**Comment by zencodex** [comment]
@fresco-fl2000 

support link is broken.
https://support.frescologic.com/portal/en/kb/articles/fl2000-mac-driver-beta-release

**Comment by Douglas-Strey** [comment]
Here is the link that's contain the driver:

https://support.frescologic.com/portal/en/kb/articles/fl2000-mac-driver-beta-release

And the drivers too:

Use Version 1.4.3 for older macOS versions;
Version 1.5.2 BETA for macOS Big Sur;

[Drivers-for-macOS.zip](https://github.com/FrescoLogic/FL2000/files/7436163/Drivers-for-macOS.zip)

**Comment by jfarris-yotpo** [comment]
Hello. I'm on macOS Monterey v12.6. Does FL2000 have plans to support this OS in the future? TIA.

**Comment by Infinite-8892** [comment]
Hello,
I have Ventura 13.3.1 and I originally had Windows Laptop. It worked fine. Moving to Ventura I installed the drivers I had. I saw they were noted for Big Sur and a bit below. I attempted them and It worked real bad. It did share screen, but only for a resolution lower. The default resolution is distorted and broken. Are there any supported drivers for it?

**Comment by mungaihehe** [comment]
Any updates on this? I am on Sonoma 14.1

**Comment by ozgurkazancci** [comment]
Hi, I'm on MacOS Monterey as well. Could you please kindly update the driver for Monterey version? This is not such a very new OS release anyway. It's already 3 year-old OS.

Regards.

**Comment by binnicordova** [comment]
It's down to version
MacOS TAHOE 26.1
Last MacOS version at 2026

I tried to install both versions, and no one works.
fl2000_1.4.3.dmg
175 KB

fl2000_1.5.2.dmg
157 KB


https://github.com/FrescoLogic/FL2000/issues/9#issuecomment-954047576
